apiVersion: v2
name: business-central
description: An unofficial Helm chart for Microsoft Dynamics 365 Business Central on Kubernetes
type: application
version: 2.2.12
kubeVersion: ">= 1.18.0"
appVersion: 20.0.37253.40399
keywords:
  - Microsoft
  - Dynamics 365
  - Business Central
  - ERP
home: https://dynamics.microsoft.com/en-us/business-central/
sources:
  - https://github.com/microsoft/nav-docker/
  - https://github.com/microsoft/ALAppExtensions
  - https://github.com/lippertmarkus/helm-charts/blob/master/charts/business-central
maintainers:
  - name: lippertmarkus
    email: markus9656@gmail.com
    url: https://lippertmarkus.com/
icon: https://github.com/lippertmarkus/helm-charts/raw/master/charts/business-central/logo.png
